# Generated by Django 3.0 on 2019-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Women', '0002_auto_20191209_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='name',
            new_name='분야',
        ),
        migrations.RemoveField(
            model_name='women',
            name='body',
        ),
        migrations.RemoveField(
            model_name='women',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='women',
            name='title',
        ),
        migrations.AddField(
            model_name='women',
            name='나이',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='이름',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='지역',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
