# Generated by Django 3.0 on 2019-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Man', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='man',
            name='character',
        ),
        migrations.AddField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
